vich_uploader:
    db_driver: orm

    mappings:
        property_photos:
           uri_prefix: '%property_photos%'           
           upload_destination: '%kernel.project_dir%/public%property_photos%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
 
        blogpost_photos:
           uri_prefix: '%blogpost_photos%'
           upload_destination: '%kernel.project_dir%/public%blogpost_photos%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
